"""initial schema

Revision ID: 0509ad8014d0
Revises: 
Create Date: 2026-09-02 21:00:30.591544
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0509ad8014d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=True),
    sa.Column('target_duration', sa.Float(), nullable=True),
    sa.Column('hook', sa.String(length=300), nullable=False),
    sa.Column('cta', sa.String(length=300), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.JSON(), nullable=False),
    sa.Column('plan_generated_by', sa.String(length=32), nullable=False),
    sa.Column('plan_notes', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('thumbnail_media_id', sa.String(length=32), nullable=True),
    sa.Column('last_render_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_projects_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('templates',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('recommended_duration', sa.Float(), nullable=False),
    sa.Column('min_images', sa.Integer(), nullable=False),
    sa.Column('max_images', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_templates_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('key', 'user_id', name='uq_template_key_user')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_key'), ['key'], unique=False)

    op.create_table('media',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_media_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_media_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_media_project_position', ['project_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_user_id'), ['user_id'], unique=False)

    op.create_table('audio_tracks',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('fade_in', sa.Float(), nullable=False),
    sa.Column('fade_out', sa.Float(), nullable=False),
    sa.Column('start_offset', sa.Float(), nullable=False),
    sa.Column('loop', sa.Boolean(), nullable=False),
    sa.Column('library_track_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_audio_tracks_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audio_tracks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_tracks')),
    sa.UniqueConstraint('project_id', name=op.f('uq_audio_tracks_project_id'))
    )
    op.create_table('render_jobs',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('output_media_id', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['output_media_id'], ['media.id'], name=op.f('fk_render_jobs_output_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_render_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_render_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_render_jobs'))
    )
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_render_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_render_jobs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_render_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('scenes',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('animation', sa.String(length=32), nullable=False),
    sa.Column('animation_intensity', sa.Float(), nullable=False),
    sa.Column('focus_x', sa.Float(), nullable=False),
    sa.Column('focus_y', sa.Float(), nullable=False),
    sa.Column('transition', sa.String(length=32), nullable=False),
    sa.Column('transition_duration', sa.Float(), nullable=False),
    sa.Column('background_color', sa.String(length=9), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=False),
    sa.Column('texts', sa.JSON(), nullable=False),
    sa.Column('ai_motion', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration > 0', name=op.f('ck_scenes_duration_positive')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_scenes_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes')),
    sa.UniqueConstraint('project_id', 'order_index', name='uq_scene_order')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_project_id'), ['project_id'], unique=False)

    op.create_table('voice_overs',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('media_id', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('voice_id', sa.String(length=120), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('duck_music_to', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_voice_overs_media_id_media'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_voice_overs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voice_overs')),
    sa.UniqueConstraint('project_id', name=op.f('uq_voice_overs_project_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_overs')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_project_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('render_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_render_jobs_user_id'))
        batch_op.drop_index('ix_render_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_render_jobs_project_id'))

    op.drop_table('render_jobs')
    op.drop_table('audio_tracks')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_user_id'))
        batch_op.drop_index('ix_media_project_position')
        batch_op.drop_index(batch_op.f('ix_media_project_id'))

    op.drop_table('media')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_key'))

    op.drop_table('templates')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_user_updated')
        batch_op.drop_index(batch_op.f('ix_projects_user_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
